version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db
        networks:
            - laravel-network

    webserver:
        image: nginx:alpine
        container_name: laravel-webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel-network

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-network

volumes:
    dbdata:

networks:
    laravel-network:
